#!/bin/sh

set -e
#set -x

. /usr/share/debconf/confmodule
if [ -f /usr/share/dbconfig-common/dpkg/config.sqlite3 ]; then
	. /usr/share/dbconfig-common/dpkg/config.sqlite3
	dbc_go db-test-sqlite3 $@
fi
