#!/bin/sh

set -e
#set -x

. /usr/share/debconf/confmodule
if [ -f /usr/share/dbconfig-common/dpkg/frontend.config.mysql ]; then
	. /usr/share/dbconfig-common/dpkg/frontend.config.mysql 
	dbc_go db-test-mysql-frontend $@
fi
