#!/bin/sh

set -e
#set -x

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/frontend.postinst.mysql 
dbc_generate_include=php:/etc/db-test-mysql-frontend/debian-db.php
dbc_go db-test-mysql-frontend $@

#DEBHELPER#
